

import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import Footer from "./(Common-Components)/Footer";
import Background2 from "./(All-Components)/(Shard-Component)/Background2";
import { Navbar } from "./(Common-Components)/Navbar";




 
// Load the Inter font
const inter = Inter({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.className}>
      <body >
        <Background2/>
        <Navbar></Navbar>
        <main>

          {children}
        </main>
        <Footer></Footer>

      </body>
    </html>
  );
}
